---
title: "R Notebook"
output: html_notebook
---

```{r}

library(tidytext)
library(janeaustenr)
library(dplyr)
library(stringr)

austen_books <- austen_books()

tidy_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]", 
                                                 ignore_case = TRUE)))) %>%
  ungroup() %>%
  unnest_tokens(word, text)

```

```{r}
library(tidyr)

jane_austen_sentiment <- tidy_books %>%
  inner_join(get_sentiments("bing")) %>%
  count(book, index = linenumber %/% 10, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)

```
```{r}

library(ggplot2)

ggplot(jane_austen_sentiment, aes(index, sentiment, fill = book)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~book, ncol = 2, scales = "free_x")

```


```{r}

afin <- get_sentiments("afinn")

data <- tidy_books %>% inner_join(afin, by = "word")
grouped <- data %>% mutate(index = linenumber %/% 25) %>%
  group_by(book, index) %>%
  summarise(score = sum(value))

ggplot(grouped, aes(index, score, fill = book)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~book, ncol = 2, scales = "free_x")

```

```{r}
library(tidytext)
library(stringr)

Sys.setlocale("LC_ALL", 'Macedonian')

tweets <- read.csv("onlytweets.csv", encoding="UTF-8")
tweets$text <- as.character(tweets$text)


```

```{r}


mkarin <- read.csv("mk-AFINN-111.txt", encoding="UTF-8")
mkarin$word <- as.character(mkarin$word)
mkarin$score <- as.integer(mkarin$score)

twords <- tweets %>% 
  unnest_tokens(word, text, token = "words")

wordswithscore <- twords %>% inner_join(mkarin, by = "word")
sumscore <- wordswithscore %>% group_by(id) %>% summarise(score = sum(score))

tweetswithscore <- tweets %>% inner_join(sumscore, by = "id") %>% arrange(score)

con<-file('tweetswithscore.csv',encoding="UTF-8")
write.csv(tweetswithscore, file=con, fileEncoding = "UTF-8")

```